version: "3"

######### Services ###################################

services:
  nginx:
    container_name: app_nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    container_name: app_php-fpm
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src/laravel-sanctum:/var/www/src/laravel-sanctum
    working_dir: /var/www/src/laravel-sanctum

  mysql:
    container_name: app_mysql
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ROOT_PASSWORD=laravel

  node:
    container_name: app_node
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./src/vue-sanctum:/var/www/src/vue-sanctum
    working_dir: /var/www/src/vue-sanctum
    tty: true

######### Volumes ###################################

volumes:
  mysql-volume:
